### ISSUE TITLE
When customer is not selecting template on gift card product edit page then a defaule template should selected 

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#7]
When customer is not selecting template on gift card product edit page then a default template should be selected 
![image](https://user-images.githubusercontent.com/25762796/64022759-83c61900-cb54-11e9-9a0d-9c2881a3ff3f.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
The issue still exists in the front-end
![image](https://user-images.githubusercontent.com/25762796/64843762-94ca5c00-d623-11e9-9806-3cddb5b09279.png)

**Comment by indresh-cedcoss** [comment]
fixed
