### ISSUE TITLE
Extra Space is displaying on the product page below the price section

### ISSUE THREAD

**Issue by anshucedcoss** [MakeWebBetter/woocommerce-gift-cards-lite#8]
Extra Space is displaying on the product page below the price section
![image](https://user-images.githubusercontent.com/25762796/64025064-7e1f0200-cb59-11e9-9f3a-20f68d165316.png)

**Comment by Snehlata-Sharma** [comment]
fixed

**Comment by anshucedcoss** [comment]
Still having issue-

![image](https://user-images.githubusercontent.com/25762796/64844224-c7288900-d624-11e9-927d-4efa00ea0d8a.png)

**Comment by indresh-cedcoss** [comment]
fixed
